apiVersion: v1
kind: Service
metadata:
  name: spring-cache-multi-service
  labels:
     app: spring-cache-multi
spec:
  selector:
    app: spring-cache-multi
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort
      